-- AlterEnum: Add new audit action types
ALTER TYPE "AuditAction" ADD VALUE 'USER_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'USER_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'ORDER_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'ORDER_VIEWED';
ALTER TYPE "AuditAction" ADD VALUE 'ORDER_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'ORDER_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'ORDER_EXPORTED';
ALTER TYPE "AuditAction" ADD VALUE 'RECIPE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'RECIPE_VIEWED';
ALTER TYPE "AuditAction" ADD VALUE 'RECIPE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'RECIPE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'RECIPE_EXPORTED';
ALTER TYPE "AuditAction" ADD VALUE 'WORKLOG_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'WORKLOG_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'WORKLOG_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'MARKETING_GENERATED';
ALTER TYPE "AuditAction" ADD VALUE 'MARKETING_EXPORTED';
ALTER TYPE "AuditAction" ADD VALUE 'AI_GRANULATION_ANALYZED';
ALTER TYPE "AuditAction" ADD VALUE 'AI_RECIPE_GENERATED';
ALTER TYPE "AuditAction" ADD VALUE 'AI_CHAT_INTERACTION';
ALTER TYPE "AuditAction" ADD VALUE 'AI_IMAGE_GENERATED';

